"""점수 계산에 쓰이는 가중치/임계값 상수.

값은 전부 원본 Andys_QIP2.py의 수식과 동일하며, 이름만 붙였다.
"""

VC1_DIVISOR: float = 5

VSCORE_EV_EBITDA_WEIGHT: float = 1.2
VSCORE_PCR_WEIGHT: float = 1.1
VSCORE_PSR_WEIGHT: float = 0.9
VSCORE_BUYBACK_YIELD_WEIGHT: float = 0.9
VSCORE_DIVIDEND_YIELD_WEIGHT: float = 0.4
VSCORE_DIVISOR: float = 5.5

MSCORE_3M_WEIGHT: float = 1.2
MSCORE_6M_WEIGHT: float = 1.6
MSCORE_DIVISOR: float = 3.8

FSCORE_INSIDER_BUY_WEIGHT: float = 0.6
FSCORE_EPSGROWTH_WEIGHT: float = 1.4
FSCORE_REVENUEGROWTH_WEIGHT: float = 1.2
FSCORE_DIVISOR: float = 4.2

FINALSCORE_VSCORE_WEIGHT: float = 0.63
FINALSCORE_MSCORE_WEIGHT: float = 0.37

EQC_ARP_WEIGHT: float = 1.7
EQC_COVERAGE_RATIO_WEIGHT: float = 1.3

VALUE_RISK_DEBT_GROWTH_THRESHOLD: float = 15
VALUE_RISK_PBR_THRESHOLD: float = 40
GROWTH_RISK_EPSGROWTH_THRESHOLD: float = 30
GROWTH_RISK_REVENUEGROWTH_THRESHOLD: float = 30

QUANT_SCORE_DIVISOR: int = 4
RELIABILITY_SCALE: float = 100
